### PR TITLE
Bump up lts to 12.26

### PR DESCRIPTION
**Pull request by pva701**
If you have Linux as OS, plz build the whole repo to ensure that loot-networks builds.
I couldn't build it for MacOS due to some unsupported dependencies used by zeromq.

### CODE REVIEW

**Comment by gromakovsky** [comment]
> 12.26

Why not 13.smth?

**Comment by flyingleafe** [comment]
It builds.

**Comment by flyingleafe** [comment]
@gromakovsky because `lts-12.26` is the one which is currently used by our Nix CI, so that e. g. Agora project uses exactly it.

**Comment by gromakovsky** [comment]
Okay, I wish there was a :slowpock: reaction on GitHub :pk:

**Comment by pva701** [comment]
@gromakovsky I've removed `log-warper` dependency

**Comment by pva701** [comment]
@gromakovsky plz don't merge it because tests fail due to fail caused `mappend` in vinyl-0.8

**Comment by kirelagin** [comment]
Obsolete due to #50.

**Pull request closed without merging**
